site_name: Studies De Jure
site_url: https://studies-de-jure.readthedocs.io/

theme: 
  name: material
  custom_dir: overrides
  font:
    text: Roboto
  favicon: images/favicon.png
  logo: images/logo1.png
  palette:  
  - media: "(prefers-color-scheme: light)"    
    scheme: default
    primary: blue grey
    accent: blue 
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode  
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue grey
    accent: blue
    toggle:
      icon: material/brightness-4
      name: Switch to light mode  
  features:
    - header.autohide
    - navigation.top
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - navigation.footer   
    - toc.follow
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    
  icon:
    admonition:
      abstract: fontawesome/solid/book
      tip: octicons/pin-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      quote: fontawesome/solid/quote-left

markdown_extensions:
  - attr_list
  - footnotes
  - abbr
  - def_list
  - md_in_html
  - smarty
  - callouts
  - mdx_truly_sane_lists
  - toc:
      toc_depth: 4
      permalink: true
      permalink_title: Anchor link to this section for reference

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tabbed:
      alternate_style: true

  - admonition
  - pymdownx.details
  - pymdownx.betterem
  - pymdownx.blocks.caption
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/glossary.md
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.extra
  - pymdownx.b64
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

watch:
  - includes

plugins:
  - search
  - mkdocs-video
  - quizdown
  - autolinks
  - literate-nav:
      nav_file: SUMMARY.md

extra_css:
  - stylesheets/extra.css
  - stylesheets/open_in_new_tab.css
  - stylesheets/glossary.css
  - stylesheets/overlay.css

extra_javascript:
  - javascripts/extra.js
  - javascripts/open_in_new_tab.js
  - javascripts/glossary_data.js
  - javascripts/glossary_auto.js
  - javascripts/overlay.js
  - javascripts/quizdown.js
  - javascripts/quizdownHighlight.js
  - javascripts/quizdownKatex.js
  - javascripts/quizdown_init.js
