site_name: Studies De Jure


nav:
  - Home: index.md
  - About: about.md

theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expandable
    - navigation.sections
    - navigation.instant

extra_css:
  - stylesheets/custom.css
extra_javascript:
  - javascripts/custom.js
